<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Phase 8b (B4) — table du transport Messenger `async`/`failed`.
 *
 * Le cycle proactif (§25.1) est désormais REDISPATCHÉ sur le transport `async`
 * (Schedule), pour hériter de la retry_strategy et du failure_transport (§25.4)
 * comme café/vote. En prod le DSN est `doctrine://default?auto_setup=0` : la
 * création de schéma à la volée est désactivée (pas de DDL runtime), c'est donc
 * CETTE migration qui possède `messenger_messages`. Idempotente : sautée si la
 * table existe déjà (créée par `messenger:setup-transports` en local/e2e).
 */
final class Version20260628130000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create messenger_messages table for the async/failed Doctrine transport (§25.4).';
    }

    public function up(Schema $schema): void
    {
        $this->skipIf($schema->hasTable('messenger_messages'), 'messenger_messages existe déjà.');

        $this->addSql(<<<'SQL'
            CREATE TABLE messenger_messages (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                body TEXT NOT NULL,
                headers TEXT NOT NULL,
                queue_name VARCHAR(190) NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                PRIMARY KEY(id)
            )
            SQL);
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DB ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('COMMENT ON COLUMN messenger_messages.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN messenger_messages.available_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN messenger_messages.delivered_at IS \'(DC2Type:datetime_immutable)\'');
    }

    public function down(Schema $schema): void
    {
        $this->skipIf(!$schema->hasTable('messenger_messages'), 'messenger_messages absente.');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
