<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Phase 6b — Outbox transactionnel.
 *
 * Crée la table outbox (§20.6) : un événement de domaine y est écrit dans la même
 * transaction que sa mutation métier (atomicité), puis relayé une fois vers Mercure
 * (at-least-once). `id` est une identité monotone = ordre d'écriture/relais. Les
 * index servent le balayage du relais (lignes non publiées) et le relais EN ORDRE
 * par édition.
 */
final class Version20260628000000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create outbox table (transactional outbox + relay).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(
            'CREATE TABLE outbox ('
            .'id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, '
            .'friday_date VARCHAR(10) NOT NULL, '
            .'type VARCHAR(64) NOT NULL, '
            .'payload TEXT NOT NULL, '
            .'created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, '
            .'published_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, '
            .'attempts INT NOT NULL, '
            .'PRIMARY KEY (id))',
        );
        $this->addSql('CREATE INDEX idx_outbox_pending ON outbox (published_at)');
        $this->addSql('CREATE INDEX idx_outbox_edition_order ON outbox (friday_date, id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE outbox');
    }
}
